import Ruby.Netlist

/-!
# SystemVerilog

Emit a circuit as a flat SystemVerilog module of Xilinx UNISIM instances
(`LUT1`–`LUT6`, `CARRY4`, `FDCE`) for Vivado. Each instance carries:

* `RLOC = "X<x>Y<y/4>"`: its slice relative to the macro origin,
* `BEL`: its site in the slice (`A6LUT`–`D6LUT` or `AFF`–`DFF` from `y % 4`, or
  `CARRY4`),
* `DONT_TOUCH`: so synthesis keeps the placed structure (for example the two
  equal XNOR columns of a two-sorter cell).

All instances of the module form one relationally placed macro. For very
large macros, `Placement.absolute` instead pins every instance with
`LOC = "SLICE_X<x0+x>Y<y0+y/4>"`: the same layout at a fixed origin, which
spares Vivado from building the macro's shape.
-/

namespace Ruby

open Shape

def Net.toSV : Net → String
  | .const false => "1'b0"
  | .const true => "1'b1"
  | .node i => s!"n{i}"
  | .port name path => name ++ String.join (path.map fun i => s!"[{i}]")

/-- A concatenation, most significant net first. -/
def concatSV (nets : List Net) : String :=
  "{" ++ ", ".intercalate (nets.reverse.map Net.toSV) ++ "}"

def hexString (digits value : Nat) : String :=
  let s := String.ofList (Nat.toDigits 16 value)
  String.ofList (List.replicate (digits - s.length) '0') ++ s

def lutBel (y : Nat) : String := #["A6LUT", "B6LUT", "C6LUT", "D6LUT"][y % 4]!

def ffBel (y : Nat) : String := #["AFF", "BFF", "CFF", "DFF"][y % 4]!

/-- How placement is expressed: a relocatable macro (`RLOC`) or absolute sites
(`LOC`) with the macro origin at slice `(x0, y0)`. -/
inductive Placement where
  | relative
  | absolute (x0 y0 : Nat)

def Placement.attribute (p : Placement) (x y : Nat) : String :=
  match p with
  | .relative => s!"RLOC = \"X{x}Y{y / 4}\""
  | .absolute x0 y0 => s!"LOC = \"SLICE_X{x0 + x}Y{y0 + y / 4}\""

def Inst.attributes (p : Placement) (i : Inst) (bel : String) : String :=
  s!"(* DONT_TOUCH = \"true\", {p.attribute i.x i.y}, BEL = \"{bel}\" *)"

def Inst.toSV (p : Placement) (clk rst : String) (i : Inst) : String :=
  match i.kind with
  | .lut k f ins o =>
      let pins := ((List.ofFn ins).zipIdx.map fun (n, j) => s!".I{j}({n.toSV})") ++
        [s!".O({(Net.node o).toSV})"]
      s!"  {i.attributes p (lutBel i.y)}\n  LUT{k} #(.INIT({2 ^ k}'h{hexString ((2 ^ k + 3) / 4) (lutInit k f)})) " ++
        s!"lut_{i.id} ({", ".intercalate pins});"
  | .carry4 ci cy di s o =>
      let outs (base : Nat) := (List.range 4).map fun j => Net.node (base + j)
      s!"  {i.attributes p "CARRY4"}\n  CARRY4 carry4_{i.id} (.CI({ci.toSV}), .CYINIT({cy.toSV}), " ++
        s!".DI({concatSV (List.ofFn di)}), .S({concatSV (List.ofFn s)}), " ++
        s!".O({concatSV (outs o)}), .CO({concatSV (outs (o + 4))}));"
  | .fdce d q =>
      s!"  {i.attributes p (ffBel i.y)}\n  FDCE #(.INIT(1'b0)) fdce_{i.id} (.C({clk}), .CE(1'b1), " ++
        s!".CLR({rst}), .D({d.toSV}), .Q({(Net.node q).toSV}));"

/-- Packed dimensions of a port of shape `s`: vectors of vectors of bits. -/
def Shape.svDims : Shape → Option (List Nat)
  | .bit => some []
  | .vec n a => (Shape.svDims a).map (n :: ·)
  | .pair .. => none

def svType (dims : List Nat) : String :=
  "logic" ++ String.join (dims.map fun n => s!" [{n - 1}:0]")

def InstKind.isRegister : InstKind → Bool
  | .fdce .. => true
  | _ => false

/-- A SystemVerilog module for a circuit with input port `a` and output port `b`.
Sequential circuits get a clock `clk` and an active-low reset `rstN`. -/
def Circuit.toSystemVerilog {a b : Shape} (c : Circuit a b) (name : String)
    (placement : Placement := .relative) : String := Id.run do
  let (out, st) := c.netlist "a"
  let sequential := st.insts.any (·.kind.isRegister)
  let aDims := (Shape.svDims a).getD []
  let bDims := (Shape.svDims b).getD []
  let ports :=
    (if sequential then ["  input  logic clk", "  input  logic rstN"] else []) ++
      [s!"  input  {svType aDims} a", s!"  output {svType bDims} b"]
  let decls := (List.range st.nextNode).map (s!"n{·}")
  let declLines := (decls.toChunks 16).map fun ns => "  logic " ++ ", ".intercalate ns ++ ";"
  let assigns := (Shape.leaves b out).map fun (path, n) =>
    "  assign b" ++ String.join (path.map fun i => s!"[{i}]") ++ s!" = {n.toSV};"
  let header := s!"// Generated by ruby-lean from a verified Ruby circuit description. Do not edit.\n" ++
    s!"// {st.insts.size} primitives in a {c.size.1} x {(c.size.2 + 3) / 4} slice " ++
      (match placement with
       | .relative => "relationally placed macro.\n\n"
       | .absolute x0 y0 => s!"block placed at SLICE_X{x0}Y{y0}.\n\n") ++
    s!"module {name} (\n" ++ ",\n".intercalate ports ++ "\n);\n"
  let resetLines := if sequential then ["  logic rst;", "  assign rst = ~rstN;"] else []
  let body := resetLines ++ declLines ++ (st.insts.toList.map (Inst.toSV placement "clk" "rst")) ++ assigns
  header ++ "\n".intercalate body ++ s!"\nendmodule : {name}\n"

/-- A self-checking testbench for a sorter of `n` words of `w` bits with
latency `latency`: random words enter every cycle and the outputs `latency`
cycles later must be the inputs, sorted. -/
def sorterTestbench (name : String) (n w latency cycles : Nat) : String :=
  s!"// Generated by ruby-lean. Self-checking testbench for {name}.
`timescale 1ns / 1ps
module {name}_tb;
  localparam int N = {n};
  localparam int W = {w};
  localparam int L = {latency};
  localparam int CYCLES = {cycles};

  logic clk = 1'b0;
  logic rstN = 1'b0;
  logic [N-1:0][W-1:0] a;
  logic [N-1:0][W-1:0] b;
  logic [N-1:0][W-1:0] expected [$];
  int checked = 0;
  int errors = 0;

  {name} dut (.clk(clk), .rstN(rstN), .a(a), .b(b));

  always #5 clk = ~clk;

  function automatic logic [N-1:0][W-1:0] sorted(input logic [N-1:0][W-1:0] v);
    logic [W-1:0] key;
    int j;
    for (int i = 1; i < N; i++) begin
      key = v[i];
      j = i - 1;
      while (j >= 0 && v[j] > key) begin
        v[j + 1] = v[j];
        j = j - 1;
      end
      v[j + 1] = key;
    end
    return v;
  endfunction

  initial begin
    a = '0;
    // Hold reset past the 100 ns global set/reset pulse of the UNISIM library.
    repeat (12) @(negedge clk);
    rstN = 1'b1;
    repeat (2) @(negedge clk);
    for (int t = 0; t < CYCLES + L; t++) begin
      @(negedge clk);
      if (expected.size() == L) begin
        logic [N-1:0][W-1:0] e;
        e = expected.pop_front();
        checked++;
        if (b !== e) begin
          errors++;
          if (errors <= 10) $display(\"MISMATCH at cycle %0d: got %h expected %h\", t, b, e);
        end
      end
      for (int i = 0; i < N; i++) a[i] = W'($urandom);
      if (t < 3) for (int i = 0; i < N; i++) a[i] = (t == 0) ? W'(N - 1 - i) : ((t == 1) ? '0 : '1);
      expected.push_back(sorted(a));
    end
    if (errors == 0) $display(\"PASS {name}: %0d vectors sorted correctly with latency %0d\", checked, L);
    else $display(\"FAIL {name}: %0d of %0d vectors wrong\", errors, checked);
    $finish;
  end
endmodule : {name}_tb
"

end Ruby
